## numpy arrays and basics


In [20]:
import numpy as np

###creating array from lists

In [21]:
arr_1D = np.array([1,2,3,4,5])
print("1D array:",arr_1D)

arr_2D = np.array([[1,2,3],[5,6,7]])
print("2D array:",arr_2D)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [5 6 7]]


### Creating array form scratch

In [23]:
import numpy as np
zeros = np.zeros((3,4))
print("Zeroes array:\n", zeros )

ones = np.ones((2,3))
print("ones array:\n",ones)

full = np.full((2,3),6)
print("full array:\n",full)

random = np.random.rand(2,4)
print("random array:\n",random)

sequence = np.arange(0,10,2)
print("sequence array:\n",sequence)

Zeroes array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[6 6 6]
 [6 6 6]]
random array:
 [[0.00329721 0.70339087 0.2851089  0.01575724]
 [0.28797811 0.36472308 0.33603717 0.83457092]]
sequence array:
 [0 2 4 6 8]


### vector,matrix,tensor

In [29]:
vector = np.array([1,2,3,4,5])
print("vector:",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix:\n",matrix)

tensor = np.array([[[1,2],[3,4]],
                 [[5,6],[7,8] ]])
print("tensor:\n",tensor)

vector: [1 2 3 4 5]
matrix:
 [[1 2 3]
 [4 5 6]]
tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
