### Numpy Array operations

In [2]:
import numpy as np

In [3]:
arr = np.array([0,1,2,3,4,5,6,7,8])

print("Basic slicing:\n",arr[2:7])
print("step slicing:\n",arr[0:2:8])
print("Negative slicing:\n",arr[-2])

Basic slicing:
 [2 3 4 5 6]
step slicing:
 [0]
Negative slicing:
 7


In [7]:
arr_2D = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("specific Element:\n",arr_2D[1,1])
print("Entire row:\n",arr_2D[1])
print("Entire row:\n",arr_2D[:,1])

specific Element:
 5
Entire row:
 [4 5 6]
Entire row:
 [2 5 8]


### Sorting

In [15]:
unsorted_arr = np.array([1,4,8,3,2,0,4,6])
print("Sorted array:\n",np.sort(unsorted_arr))

unsorted_2D_arr = np.array([[1,3],
                            [2,7],
                            [9,0]])
print("sorted 2D array by column:\n",np.sort(unsorted_2D_arr,axis=0))

Sorted array:
 [0 1 2 3 4 4 6 8]
sorted 2D array by column:
 [[1 0]
 [2 3]
 [9 7]]


### Filter

In [22]:
arr = np.array([1,2,3,12,56,78,90,33,45])
even_arr = arr[arr%2==0]
print("Even array:",even_arr)

Even array: [ 2 12 56 78 90]


### Filter with mask

In [23]:
mask = arr > 4
print("Number greater than 4:",arr[mask])

Number greater than 4: [12 56 78 90 33 45]


### Fancy indexing vs np.where()

In [25]:
indices=[1,2,3]
print(arr[indices])

where_result = np.where(arr>3)
print (where_result)
print("NP where:\n",arr[where_result])

[ 2  3 12]
(array([3, 4, 5, 6, 7, 8]),)
NP where:
 [12 56 78 90 33 45]


In [27]:
condition_arr = np.where(arr>4,True,False)
print(condition_arr)


[False False False  True  True  True  True  True  True]


### Ading and removing data

In [29]:
arr1 = ([1,2,3])
arr2 = ([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


###  Array compatibility

In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatibility shapes:", a.shape == b.shape)

compatibility shapes: True


In [35]:
original_arr = np.array([[1,2],[3,4]])
new_row  = np.array([5,6])

with_new_row = np.vstack((original_arr,new_row)) 
print(original_arr)
print("with new row:",with_new_row)

new_col = np.array([[7],[8]])
with_new_column = np.hstack((original_arr,new_col))
print("With new column:\n",with_new_column)


[[1 2]
 [3 4]]
with new row: [[1 2]
 [3 4]
 [5 6]]
With new column:
 [[1 2 7]
 [3 4 8]]


In [36]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,1)
print("Array after deletion:",deleted)

Array after deletion: [1 3 4 5]
